TicketOnlineShop/TicketOnlineShop/Controllers/EventsController.cs
using Microsoft.AspNetCore.Mvc;
using TicketOnlineShop.Models.Abstractions;

namespace TicketOnlineShop.Controllers
{
    public class EventsController : Controller
    {
        private IEventService _eventService;
        private ITicketService _ticketService;

        public EventsController(IEventService eventService, ITicketService ticketService)
        {
            _eventService = eventService;
            _ticketService = ticketService;
        }

        public IActionResult Index()
        {   
            return View(_eventService.GetAllEvents());
        }

        [HttpGet]
        public IActionResult AvailableTickets(string eventName)
        {
            var currentTickets = _ticketService.GetTicktesByEventName(eventName);
            
            return View(currentTickets);
        }
    }
}

TicketOnlineShop/TicketOnlineShop/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TicketOnlineShop.Models;
using TicketOnlineShop.Models.Abstractions;

namespace TicketOnlineShop.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private ITicketService _ticketService;
        private IOrderService _orderService;
        private UserManager<MyUser> _userManager;

        public ProfileController(ITicketService ticketService, IOrderService orderService
            , UserManager<MyUser> userManager)
        {
            _ticketService = ticketService;
            _orderService = orderService;
            _userManager = userManager;
        }

        public ActionResult Index()
        {
            var user = _userManager.FindByNameAsync(User.Identity.Name).Result;
            return View(user);
        }

        public ActionResult MyTickets()
        {
            return View(_ticketService.GetAllTickets());
        }

        public ActionResult MyOrders()
        {            
            return View(_orderService.GetAllOrders());
        }
    }
}

TicketOnlineShop/TicketOnlineShop/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TicketOnlineShop.Models
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject SignInManager<MyUser> SignInManager
@inject UserManager<MyUser> UserManager
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="headerContainer">
        <div class="leftPartHeader">
            <menu>
                <li>
                    <a asp-controller="Home" asp-action="Index">@Localizer["MainPage"]</a>
                </li>
                <li>
                    <a asp-controller="Events" asp-action="Index">@Localizer["Events"]</a>
                </li>
                <li>
                    <a asp-controller="Profile" asp-action="MyTickets">@Localizer["MyTickets"]</a>
                </li>
                <li>
                    <a asp-controller="Profile" asp-action="MyOrders">@Localizer["MyOrders"]</a>
                </li>
                @if (User.Identity.Name == "Admin")
                {
                    <li>
                        <a asp-controller="Admin" asp-action="Index">@Localizer["OnlyForAdmin"]</a>
                    </li>
                }
            </menu>
        </div>
        <div class="rightPartHeader">
            <menu>
                <li>
                    <a asp-controller="Profile" asp-action="Index">@Localizer["Hello"], @UserManager.GetUserName(User)!</a>
                </li>
                <li>
                    <form asp-controller="Account" asp-action="Logout" method="post">
                        <button class="buttonAsAnchor" type="submit">@Localizer["LogOut"]</button>
                    </form>
                </li>
                <li>
                    <form asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post">
                        <label class="language">@Localizer["Language"]:</label>
                        <select name="culture" onchange="this.form.submit();" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
                    </form>
                </li>
            </menu>
        </div>
    </div>
}
else
{
    <div class="headerContainer">
        <div class="leftPartHeader">
            <menu>
                <li>
                    <a asp-controller="Home" asp-action="Index">@Localizer["MainPage"]</a>
                </li>
                <li>
                    <a asp-controller="Events" asp-action="Index">@Localizer["Events"]</a>
                </li>
            </menu>
        </div>
        <div class="rightPartHeader">
            <menu>
                <li>
                    <a asp-controller="Account" asp-action="Login">@Localizer["LogIn"]</a>
                </li>
                <li>
                    <form asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" class="test">
                        <label class="language">@Localizer["Language"]:</label>
                        <select name="culture" onchange="this.form.submit();" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
                    </form>
                </li>
            </menu>
        </div>
    </div>

}

TicketOnlineShop/TicketOnlineShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/reset.css" />
    <link rel="stylesheet" type="text/css" href="~/css/site.css" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"] Ticker re-sailing store</title>    
</head>
<body>
    <div class="wrapper">
        <header>
            @await Html.PartialAsync("_HeaderPartial")
        </header>
        <main>            
            @RenderBody()            
        </main>
        <footer>
            <div>&copy; 2017 - @Localizer["Author"]</div>
        </footer>  
    </div>    
</body>
</html>